/**
 * Input schemas for the interim order and customer actions (S1-P04-T007; rebuilt in S1-P12 / S1-P13).
 *
 * Every schema is a `strictObject`: an unknown key — `tenantId`, a price, a total, a tax amount — is rejected with
 * 422 VALIDATION_ERROR instead of being dropped (SC-VAL-01, SC-TEN-01, ADV-007, ADV-008). Prices, totals and the
 * tenant always come from the server.
 */
import { OrderPriority, OrderStatus, OrderType } from "@prisma/client";
import { z } from "zod";
import { boundedText, e164Field, emailField, optionalText, strictObject, uuidParam } from "./core";

export const TABLE_LABEL_PATTERN = /^[A-Za-z0-9 -]*$/;

/** One cart line. Prices are never accepted from the client: the server reads them from the tenant's catalogue. */
export const orderLineSchema = strictObject({
  menuItemId: uuidParam,
  /** Required when the item has active variants, refused when it has none (ADR-010 §2). */
  variantId: uuidParam.optional(),
  addonIds: z
    .array(uuidParam)
    .max(10, "Choose at most 10 add-ons for one line")
    .refine((ids) => new Set(ids).size === ids.length, "Each add-on can be chosen once")
    .optional()
    .default([]),
  quantity: z
    .number()
    .int("Quantity must be a whole number")
    .min(1, "Quantity must be at least 1")
    .max(99, "Quantity must be at most 99"),
  specialInstructions: optionalText(280, "Special instructions"),
});

export const orderCustomerSchema = strictObject({
  name: boundedText(120, { label: "Customer name" }),
  phone: z
    .union([z.literal(""), e164Field])
    .optional()
    .transform((value) => value || null),
  email: z
    .union([z.literal(""), emailField])
    .optional()
    .transform((value) => value || null),
  notes: optionalText(500, "Customer notes"),
});

/**
 * SA-ORD-01 — staff order entry (S1-P12-T004). `idempotencyKey` is generated by the client per submit attempt: a
 * repeat returns the original order instead of creating a second one (ADR-010 §7). Either link an existing customer
 * by id or supply a new one — never both, and creating one needs `customer:create`.
 */
export const createOrderSchema = strictObject({
  idempotencyKey: uuidParam,
  orderType: z.nativeEnum(OrderType),
  tableLabel: z
    .string()
    .trim()
    .max(20, "Table label must be at most 20 characters")
    .regex(TABLE_LABEL_PATTERN, "Table label may contain letters, digits, spaces and dashes")
    .optional()
    .transform((value) => value || null),
  notes: optionalText(500, "Notes"),
  priority: z.nativeEnum(OrderPriority).optional(),
  customerId: uuidParam.optional(),
  customer: orderCustomerSchema.optional(),
  /** Accept the order and send its tickets to the kitchen in the same transaction (needs `order:accept`). */
  sendToKitchen: z.boolean().optional().default(false),
  items: z.array(orderLineSchema).min(1, "Order must contain at least one item").max(100, "An order can have at most 100 lines"),
}).refine((input) => !(input.customerId && input.customer), {
  path: ["customer"],
  message: "Link an existing customer or add a new one, not both",
});

/** LD-ORD-01 (interim): order board filters. */
export const listOrdersSchema = strictObject({
  status: z.nativeEnum(OrderStatus).optional(),
  search: optionalText(100, "Search"),
});

/** ADR-009: one page of the order board never exceeds 200 rows, polling or not (api.md RH-ORD-01). */
export const ORDER_BOARD_LIMIT = 200;

/** LD-ORD-01 board filters: the active queue plus today's closed orders, narrowed by status, type and a search term. */
export const orderBoardFiltersSchema = strictObject({
  status: z.nativeEnum(OrderStatus).optional(),
  type: z.nativeEnum(OrderType).optional(),
  q: optionalText(100, "Search"),
});

/**
 * RH-ORD-01 poll query (S1-P12-T006). `since` is the previous response's `serverTime`, so the cursor is the server's
 * clock and never the device's. Query strings arrive as strings, so each value is coerced here.
 */
export const orderPollSchema = strictObject({
  since: z
    .string()
    .datetime({ offset: true, message: "since must be an ISO timestamp from a previous response" })
    .transform((value) => new Date(value))
    .optional(),
  status: z.nativeEnum(OrderStatus).optional(),
  type: z.nativeEnum(OrderType).optional(),
  q: optionalText(100, "Search"),
  limit: z.coerce
    .number()
    .int()
    .min(1, "limit must be at least 1")
    .max(ORDER_BOARD_LIMIT, `limit must be at most ${ORDER_BOARD_LIMIT}`)
    .optional(),
});

/** LD-ORD-02 / LD-ORD-03 reference: one order of the caller's own restaurant. */
export const orderRefSchema = strictObject({ orderId: uuidParam });

/** SA-ORD-06 — `order:update_meta`; the service refuses HIGH for a WAITER (api.md SA-ORD-06). */
export const setOrderPrioritySchema = strictObject({
  orderId: uuidParam,
  priority: z.nativeEnum(OrderPriority),
});

/** SA-ORD-05 — `order:update_meta` + `customer:read`; `null` unlinks the customer. */
export const setOrderCustomerSchema = strictObject({
  orderId: uuidParam,
  customerId: uuidParam.nullable(),
});

/**
 * SA-ORD-01 companion (S1-P12-T007): the POS asks the server to price the cart it is building, so no total is ever
 * computed in the browser (ADR-010 §3). Same line shape as the order, and equally free of price fields.
 */
export const quoteOrderSchema = strictObject({
  items: z.array(orderLineSchema).min(1, "Add at least one item").max(100, "An order can have at most 100 lines"),
});

/** Targets a user may request (security.md §3.4). NEW is only a start state; REFUNDED is set by a full refund. */
export const ORDER_TRANSITION_TARGETS = ["ACCEPTED", "PREPARING", "READY", "COMPLETED", "CANCELLED"] as const satisfies readonly OrderStatus[];
export type OrderTransitionTarget = (typeof ORDER_TRANSITION_TARGETS)[number];

/** SA-ORD-02 / SA-ORD-03 (interim): one action for every manual transition; `reason` is required for CANCELLED. */
export const updateOrderStatusSchema = strictObject({
  orderId: uuidParam,
  status: z.enum(ORDER_TRANSITION_TARGETS),
  reason: optionalText(280, "Reason"),
  expectedVersion: z.number().int().min(0).optional(),
});

/** LD-CUS-01 (interim): customer list search. */
export const listCustomersSchema = strictObject({
  query: optionalText(100, "Search"),
});

export type CreateOrderInput = z.input<typeof createOrderSchema>;
export type CreateOrderData = z.output<typeof createOrderSchema>;
export type ListOrdersInput = z.input<typeof listOrdersSchema>;
export type ListOrdersData = z.output<typeof listOrdersSchema>;
export type UpdateOrderStatusInput = z.input<typeof updateOrderStatusSchema>;
export type UpdateOrderStatusData = z.output<typeof updateOrderStatusSchema>;
export type ListCustomersInput = z.input<typeof listCustomersSchema>;
export type ListCustomersData = z.output<typeof listCustomersSchema>;
export type OrderBoardFiltersInput = z.input<typeof orderBoardFiltersSchema>;
export type OrderBoardFiltersData = z.output<typeof orderBoardFiltersSchema>;
export type OrderPollInput = z.input<typeof orderPollSchema>;
export type OrderPollData = z.output<typeof orderPollSchema>;
export type OrderRefInput = z.input<typeof orderRefSchema>;
export type SetOrderPriorityInput = z.input<typeof setOrderPrioritySchema>;
export type SetOrderPriorityData = z.output<typeof setOrderPrioritySchema>;
export type SetOrderCustomerInput = z.input<typeof setOrderCustomerSchema>;
export type SetOrderCustomerData = z.output<typeof setOrderCustomerSchema>;
export type QuoteOrderInput = z.input<typeof quoteOrderSchema>;
export type QuoteOrderData = z.output<typeof quoteOrderSchema>;
